"""Generates smaller copies of every photo in public/media for srcset, and writes
src/app/data/media.generated.ts listing the widths that exist for each file.

Run from the project root after adding or replacing a photo:
    python scripts/responsive-images.py

Needs ImageMagick 7 (`magick`) on the PATH. Copies are named photo-800.webp and
so on; the original keeps its name and serves as the largest width.
"""

import json
import pathlib
import re
import subprocess

MEDIA = pathlib.Path('public/media')
MANIFEST = pathlib.Path('src/app/data/media.generated.ts')
WIDTHS = [480, 800, 1200]
VARIANT = re.compile(r'-\d+$')


def width_of(path: pathlib.Path) -> int:
    return int(subprocess.check_output(['magick', 'identify', '-format', '%w', str(path)], text=True))


manifest = {}

for original in sorted(MEDIA.glob('*.webp')):
    if VARIANT.search(original.stem):
        continue

    full = width_of(original)
    widths = []

    for width in WIDTHS:
        if width >= full:
            continue

        target = original.with_name(f'{original.stem}-{width}.webp')
        subprocess.run(['magick', str(original), '-resize', f'{width}x', '-quality', '78', str(target)], check=True)
        widths.append(width)

    manifest[f'/media/{original.name}'] = widths + [full]
    print(f'{original.name}: {widths + [full]}')

MANIFEST.write_text(
    '// Generated by scripts/responsive-images.py. Do not edit by hand: rerun the\n'
    '// script after adding or replacing a photo in public/media.\n\n'
    f'export const MEDIA_WIDTHS: Record<string, number[]> = {json.dumps(manifest, indent=4)};\n',
    encoding='utf-8'
)
