// Generated by scripts/responsive-images.py. Do not edit by hand: rerun the
// script after adding or replacing a photo in public/media.

export const MEDIA_WIDTHS: Record<string, number[]> = {
    "/media/cave.webp": [
        480,
        800,
        1000
    ],
    "/media/combi.webp": [
        480,
        800,
        1000
    ],
    "/media/couple-dawn.webp": [
        480,
        800,
        1086
    ],
    "/media/couple-embrace.webp": [
        480,
        800,
        1200,
        1600
    ],
    "/media/event-banner.webp": [
        480,
        800,
        1200,
        1280
    ],
    "/media/event-couple.webp": [
        480,
        800,
        1200,
        1280
    ],
    "/media/event-drummer.webp": [
        480,
        800,
        854
    ],
    "/media/event-poster.webp": [
        480,
        800,
        1024
    ],
    "/media/hero-poster.webp": [
        480,
        800,
        1200,
        1920
    ],
    "/media/woman-pyramids.webp": [
        480,
        800,
        1200,
        1254
    ]
};
